language: python
python:
  - "2.7"
services:
  - mongodb

before_install:
  - pip install --upgrade pip
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

install:
  - pip install -r requirements.txt

script:
  - python tests.py
